### ISSUE TITLE
演练工具安装失败:/bin/sh: ansible: command not found

### ISSUE THREAD

**Issue by Li-Vincent** [chaosblade-io/chaos-platform#14]
http://xxxx:8080/api/DeployChaostoolsToHost

Request:
{
	machineId: "1365143675318001665"
	name: "chaosblade"
	url: "https://chaosblade.oss-cn-hangzhou.aliyuncs.com/agent/github/0.9.0/chaosblade-0.9.0-linux-amd64.tar.gz"
	version: "0.9.0"
}

Response:
{
	"code": 6602,
	"message": "演练工具安装失败:/bin/sh: ansible: command not found\n",
	"success": false,
	"data": "/bin/sh: ansible: command not found\n",
	"requestId": "81e400a9b2fb480984c315d4772f4eff"
}

**Comment by Li-Vincent** [comment]
need install ansible

**Comment by wanzr** [comment]
@Li-Vincent   hello~  Do you mean need to install ansible in container ？  Because my pod already install ansible, but  when deploy ChaosTool i meet the same error。Here is the error report


{code: 6602, message: "CHAOS_TOOLS_INSTALL_FAIL:/bin/sh: 1: ansible: not found↵", success: false,…}
code: 6602
data: "/bin/sh: 1: ansible: not found↵"
message: "CHAOS_TOOLS_INSTALL_FAIL:/bin/sh: 1: ansible: not found↵"
requestId: "7854ab93c00b4e5bbcf14bcbb0aa2d16"
success: false

**Comment by Li-Vincent** [comment]
> @Li-Vincent hello~ Do you mean need to install ansible in container ？ Because my node already install ansible, but when deploy ChaosTool i meet the same error。Here is the error report
> 
> {code: 6602, message: "CHAOS_TOOLS_INSTALL_FAIL:/bin/sh: 1: ansible: not found↵", success: false,…}
> code: 6602
> data: "/bin/sh: 1: ansible: not found↵"
> message: "CHAOS_TOOLS_INSTALL_FAIL:/bin/sh: 1: ansible: not found↵"
> requestId: "7854ab93c00b4e5bbcf14bcbb0aa2d16"
> success: false

Install ansible in master server, config server IP and authorization in /etc/ansible/hosts.
